In [2]:
import numpy as np

In [3]:
l = [23245, 25, 453, 214, -1234]

In [4]:
a = np.array(l)

In [5]:
a[2:]

array([  453,   214, -1234])

In [6]:
a[2:4]

array([453, 214])

In [7]:
len(a)

5

In [8]:
a[5:1:-1]

array([-1234,   214,   453])

In [9]:
a[-5]

23245

In [18]:
b = a[2:4]

In [19]:
b

array([453, 214])

In [20]:
b[:]

array([453, 214])

In [21]:
b[:] = 222

In [22]:
b

array([222, 222])

In [23]:
a

array([23245,    25,   222,   222, -1234])

In [24]:
# Slices of arrays update original arrays, to keep changes, use copy()

In [27]:
c = a.copy()

In [28]:
c[:]

array([23245,    25,   222,   222, -1234])

In [29]:
c[:] = 111

In [30]:
c

array([111, 111, 111, 111, 111])

In [31]:
a

array([23245,    25,   222,   222, -1234])